In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df_train.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [3]:
df_train.describe()

,Unnamed: 0,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
count,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103594.000000
mean,51951.500000,64924.210502,39.379706,1189.448375,2.729683,3.060296,2.756901,2.976883,3.202129,3.250375,3.439396,3.358158,3.382363,3.351055,3.631833,3.304290,3.640428,3.286351,14.815618,15.178678
std,29994.645522,37463.812252,15.114964,997.147281,1.327829,1.525075,1.398929,1.277621,1.329533,1.349509,1.319088,1.332991,1.288354,1.315605,1.180903,1.265396,1.175663,1.312273,38.230901,38.698682
min,0.000000,1.000000,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,25975.750000,32533.750000,27.000000,414.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000
50%,51951.500000,64856.500000,40.000000,843.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,3.000000,0.000000,0.000000
75%,77927.250000,97368.250000,51.000000,1743.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,5.000000,4.000000,12.000000,13.000000
max,103903.000000,129880.000000,85.000000,4983.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1592.000000,1584.000000

## Preprocessing Data

### Handle NaN

In [4]:
# Thay thế các giá trị NaN bằng giá trị trung bình của cột Arrival Delay in Minutes
df_train['Arrival Delay in Minutes'].fillna(df_train['Arrival Delay in Minutes'].mean(), inplace=True)
df_test['Arrival Delay in Minutes'].fillna(df_test['Arrival Delay in Minutes'].mean(), inplace=True)

### Data Transformation

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in df_train.columns:
    if df_train[col].dtype == 'object':
        df_train[col] = le.fit_transform(df_train[col])
        df_test[col] = le.fit_transform(df_test[col])

## Data Normalization

In [6]:
from sklearn.preprocessing import MinMaxScaler

X_train = np.array(df_train.iloc[:, 1:-1])
y_train = np.array(df_train.iloc[:, -1])
X_test = np.array(df_test.iloc[:, 1:-1])
y_test = np.array(df_test.iloc[:, -1])

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

## Build Model

### SVM

In [7]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

svc = SVC(kernel="linear", C=1.)
svc.fit(X_train_scaled, y_train)

y_pred_svc = svc.predict(X_test_scaled)

acc_score_svm = accuracy_score(y_pred_svc, y_test)
print("accuracy:\n", acc_score_svm)

accuracy:
 0.8736910994764397

In [8]:
print(classification_report(y_test, y_pred_svc))

              precision    recall  f1-score   support

           0       0.86      0.92      0.89     14573
           1       0.89      0.81      0.85     11403

    accuracy                           0.87     25976
   macro avg       0.88      0.87      0.87     25976
weighted avg       0.88      0.87      0.87     25976

### Avoid Overfiting

#### Cross Validation => Kiểm tra model có bị overfiting không?

In [9]:
# Do dataset đã chia sẵn train và test nên ta hợp lại để chia K-Fold
X = np.concatenate((X_train_scaled, X_test_scaled), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

In [12]:
num_folds = 5

accuracy_list = []

from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

# Định nghĩa K-Fold CV
k_fold = KFold(n_splits=num_folds, shuffle=True)

# K-fold Cross Validation model evaluation
fold_idx = 1

for train_ids, val_ids in k_fold.split(X, y):

  svc = SVC(kernel="linear", C=1.)

  print("Bắt đầu train Fold ", fold_idx)

  # Train model
  svc.fit(X[train_ids], y[train_ids])

  y_pred = svc.predict(X[val_ids])
  score = accuracy_score(y[val_ids], y_pred)

  print("Đã train xong Fold ", fold_idx)

  # Thêm thông tin accuracy và loss vào list
  accuracy_list.append(score * 100)

  # Sang Fold tiếp theo
  fold_idx = fold_idx + 1

Bắt đầu train Fold  1
Đã train xong Fold  1
Bắt đầu train Fold  2
Đã train xong Fold  2
Bắt đầu train Fold  3
Đã train xong Fold  3
Bắt đầu train Fold  4
Đã train xong Fold  4
Bắt đầu train Fold  5
Đã train xong Fold  5

In [13]:
# In kết quả tổng thể
print('* Chi tiết các fold')
for i in range(0, len(accuracy_list)):
  print(f'> Fold {i+1} - Accuracy: {accuracy_list[i]}%')

print('* Đánh giá tổng thể các folds:')
print(f'> Accuracy: {np.mean(accuracy_list)} (Độ lệch +- {np.std(accuracy_list)})')

* Chi tiết các fold
> Fold 1 - Accuracy: 88.09285494302434%
> Fold 2 - Accuracy: 87.96196489066831%
> Fold 3 - Accuracy: 87.34601170311056%
> Fold 4 - Accuracy: 87.43840468124424%
> Fold 5 - Accuracy: 87.53849707422235%
* Đánh giá tổng thể các folds:
> Accuracy: 87.67554665845395 (Độ lệch +- 0.29657842160279746)

### Feature Selection

In [14]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
rfe = RFE(RandomForestClassifier(n_estimators=100, random_state=42), n_features_to_select=10)

rfe.fit(X, y)
X = rfe.transform(X)

# Split dataset thành train set và test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # already scale

In [15]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

svc = SVC(kernel="linear", C=1.)
svc.fit(X_train, y_train)

y_pred_svc = svc.predict(X_test)

acc_score_svm = accuracy_score(y_pred_svc, y_test)
print("accuracy:\n", acc_score_svm)

accuracy:
 0.8533646442870342

In [16]:
print(classification_report(y_test, y_pred_svc))

              precision    recall  f1-score   support

           0       0.86      0.89      0.87     14622
           1       0.85      0.81      0.83     11354

    accuracy                           0.85     25976
   macro avg       0.85      0.85      0.85     25976
weighted avg       0.85      0.85      0.85     25976